name: Java CI with Maven

on:
  pull_request:
    branches: [ "main" ]

jobs:
  run-test:
    name: 'Run tests'
    runs-on: ubuntu-latest
    
    steps:
    - name: Git clone
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven

    - name: Cache maven
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('./pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.5.0
            
    - name: Build with Maven
      run: mvn clean test

    - name: Attach screenshots and reports
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: screenshots-and-report
        path: |
          screenshots
          **/surefire-reports/emailable-report.html

    - name: Test Reporter
      uses: dorny/test-reporter@v1.8.0
      if: success() || failure()
      with:
          name: Test Execution Report
          path: target/surefire-reports/TEST-*.xml
          reporter: java-junit
            
