name: CI

on:
  pull_request:
    branches: [main]

jobs:
  run-test:
    name: 'Run tests'
    runs-on: ubuntu-latest

    steps:
      - name: Git clone
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('./pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build & Install
        run: mvn -B install -D skipTests --no-transfer-progress

      - name: save maven version
        run: echo "MAVEN_HOME=$(mvn -version | head -1)" >> $GITHUB_ENV

      - name: Maven test
        run: mvn -B package --file pom.xml
        env:
          CHROME_OPTIONS: --disable-gpu;--no-sandbox;--disable-dev-shm-usage;--headless;--window-size=1920,1080
          CI_RUN: true

      - name: Attach screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          path: screenshots
          
      - name: Create test report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Unit tests Report
          path: target/surefire-reports/TEST-*.xml
          reporter: java-junit
